### ISSUE TITLE
nimkernel broken when use Clang with -d or -opt flags

### ISSUE THREAD

**Issue by ghost** [dom96/nimkernel#13]
Hello, 

I had some experiment with you code, that was fun and thank for creating this example. I try to use Clang with you kernel with exact config you do, some function broken weirdly and loop QEMU BIOS when i use flag like -d:release or -opt:speed the kernel goes to that state, but it totally fine without any -d or -opt. 

I trace the culprit belong to this line : https://github.com/ArjunRangga/nimkernel/blob/clang/ioutils.nim#L77 , when it invoked by kmain.

Here my code : https://github.com/ArjunRangga/nimkernel/tree/clang .

Do you had idea what happen ? or I miss something? Anyways, It pass compilation either with flags or not.

**Comment by dom96** [comment]
No idea, but maybe you can check what the C code output looks like with and without -d:release. Might show the problem.

**Comment by ghost** [comment]
I figured out, a compiler flag caused this issue : `-O3`. Since I do diff at the C file either compile with flag or not (Thanks for the debugging idea), this issues persist because `-O3` flags exists. I think this is compiler optimization issues and the code merely fine. 

I gonna close this issue, my solution is to use lower flag like `-O1` which works after `-O2` fail as `-O3` do.
