### ISSUE TITLE
Would it be possible to integrate nimkernel with the nimble package manager?

### ISSUE THREAD

**Issue by ghost** [dom96/nimkernel#14]
Hi. I wonder if it would be possible to integrate this nimkernel with the nimble package manager. Would it be possible to integrate nimkernel with the nimble package manager?

*It's a curious and technical question, I'd be happy with any answer to this doubt I have*

**Comment by dom96** [comment]
Sure it would

**Comment by ghost** [comment]
Hi dom96. How could I do this? do you have any manual or any guide? How can I integrate the nimble package with the nim kernel?

**Comment by dom96** [comment]
just port the nakefile to Nimble's tasks, it's very similar syntax, take a look at other packages for examples and the Nimble readme.
