### ISSUE TITLE
invalid instruction suffix

### ISSUE THREAD

**Issue by lbcheng888** [dom96/nimkernel#7]
./nakefile run
/tmp/ccDbBZ4I.s: Assembler messages:
/tmp/ccDbBZ4I.s:51: Error: invalid instruction suffix for `push'
/tmp/ccDbBZ4I.s:56: Error: invalid instruction suffix for `push'
/tmp/ccDbBZ4I.s:58: Error: invalid instruction suffix for `push'
/tmp/ccDbBZ4I.s:62: Error: invalid instruction suffix for `pop'

**Comment by gaku** [comment]
It looks like toolchain's 32bit/64bit difference.  I saw the same errors.
I've built i386-elf cross compiler instead of i586-elf and the code compiled successfully without this error.
