### ISSUE TITLE
RaspberryPi conversion?

### ISSUE THREAD

**Issue by matkuki** [dom96/nimkernel#8]
Could this project be adapted for the RaspberryPi?
What would be the needed steps to take to convert it?

Thanks

**Comment by dom96** [comment]
Doing so would be a cool project. I have no idea what it would take. This project is just an adaptation of the os-dev wiki's tutorials for a simple kernel in C. I bet they have some RPi materials nowadays.

**Comment by matkuki** [comment]
@dom96 
Thanks for the information!
